language: node_js
node_js:
  - "0.10"

after_script:
  - if [[ `node --version` == *v0.10* ]]; then cat ./coverage/lcov-report/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi

env:
  global:
    - SAUCE_USERNAME="$SAUCE_DEV_NAME"
    - SAUCE_ACCESS_KEY="$SAUCE_DEV_KEY"

notifications:
  slack: mojs:n6WXx45anfQn03fJu5Yw0Btt
